# Generated by Django 5.0.6 on 2024-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishnumber',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
