# Generated by Django 5.0.6 on 2024-06-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fishdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.FloatField(verbose_name='V')),
                ('salt', models.FloatField(verbose_name='Salt')),
                ('oxygen', models.FloatField(verbose_name='Oxygen')),
                ('ntu', models.FloatField(verbose_name='NTU')),
                ('ph', models.FloatField(verbose_name='PH')),
                ('tem', models.FloatField(verbose_name='Temperature')),
            ],
        ),
    ]
