# Generated by Django 5.0.6 on 2024-06-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_information_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
