# Generated by Django 5.0.6 on 2024-06-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_information_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='date',
        ),
    ]
